### ISSUE TITLE
Write a Getting started documentation

### ISSUE THREAD

**Issue by sherry-ummen** [camunda-community-hub/eze#7]
Nice project and also I believe this is much better direction than Testcontainers. But a getting started guide would be nice to have :)

**Comment by saig0** [comment]
Fair point :smile: 

Please note that the project is very new :sparkles: I plan to update the README this week :memo:

**Comment by Zelldon** [comment]
Until we write a better readme you can take a look at the release notes https://github.com/camunda-community-hub/eze/releases/tag/0.1.0 and example usage https://github.com/camunda-community-hub/eze/blob/main/eze/src/test/kotlin/org/camunda/community/eze/EngineClientTest.kt

**Comment by saig0** [comment]
Done. I updated the README.
